# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parametros_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Param(object):
    def setupUi(self, Dialog_Param):
        Dialog_Param.setObjectName("Dialog_Param")
        Dialog_Param.resize(800, 600)
        self.text_pressao_max = QtWidgets.QTextEdit(Dialog_Param)
        self.text_pressao_max.setGeometry(QtCore.QRect(70, 130, 104, 78))
        self.text_pressao_max.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_pressao_max.setObjectName("text_pressao_max")
        self.text_temp_max = QtWidgets.QTextEdit(Dialog_Param)
        self.text_temp_max.setGeometry(QtCore.QRect(210, 130, 104, 78))
        self.text_temp_max.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_temp_max.setObjectName("text_temp_max")
        self.text_umi_max = QtWidgets.QTextEdit(Dialog_Param)
        self.text_umi_max.setGeometry(QtCore.QRect(350, 130, 104, 78))
        self.text_umi_max.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_umi_max.setObjectName("text_umi_max")
        self.text_fluxo_max = QtWidgets.QTextEdit(Dialog_Param)
        self.text_fluxo_max.setGeometry(QtCore.QRect(490, 130, 104, 78))
        self.text_fluxo_max.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_fluxo_max.setObjectName("text_fluxo_max")
        self.text_xxxxx_max = QtWidgets.QTextEdit(Dialog_Param)
        self.text_xxxxx_max.setGeometry(QtCore.QRect(630, 130, 104, 78))
        self.text_xxxxx_max.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_xxxxx_max.setObjectName("text_xxxxx_max")
        self.label_pressao_max = QtWidgets.QLabel(Dialog_Param)
        self.label_pressao_max.setGeometry(QtCore.QRect(95, 90, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pressao_max.setFont(font)
        self.label_pressao_max.setObjectName("label_pressao_max")
        self.label_temp_max = QtWidgets.QLabel(Dialog_Param)
        self.label_temp_max.setGeometry(QtCore.QRect(215, 90, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_max.setFont(font)
        self.label_temp_max.setObjectName("label_temp_max")
        self.label_umi_max = QtWidgets.QLabel(Dialog_Param)
        self.label_umi_max.setGeometry(QtCore.QRect(370, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_umi_max.setFont(font)
        self.label_umi_max.setObjectName("label_umi_max")
        self.label_fluxo_max = QtWidgets.QLabel(Dialog_Param)
        self.label_fluxo_max.setGeometry(QtCore.QRect(500, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_fluxo_max.setFont(font)
        self.label_fluxo_max.setObjectName("label_fluxo_max")
        self.label_xx_max = QtWidgets.QLabel(Dialog_Param)
        self.label_xx_max.setGeometry(QtCore.QRect(645, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_xx_max.setFont(font)
        self.label_xx_max.setObjectName("label_xx_max")
        self.label_superior = QtWidgets.QLabel(Dialog_Param)
        self.label_superior.setEnabled(False)
        self.label_superior.setGeometry(QtCore.QRect(70, 20, 661, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_superior.setFont(font)
        self.label_superior.setObjectName("label_superior")
        self.pushButton = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton.setGeometry(QtCore.QRect(70, 210, 106, 32))
        self.pushButton.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton.setObjectName("pushButton")
        self.label_pressao_max2 = QtWidgets.QLabel(Dialog_Param)
        self.label_pressao_max2.setGeometry(QtCore.QRect(105, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pressao_max2.setFont(font)
        self.label_pressao_max2.setObjectName("label_pressao_max2")
        self.label_temp_max2 = QtWidgets.QLabel(Dialog_Param)
        self.label_temp_max2.setGeometry(QtCore.QRect(245, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_max2.setFont(font)
        self.label_temp_max2.setObjectName("label_temp_max2")
        self.label_umi_max2 = QtWidgets.QLabel(Dialog_Param)
        self.label_umi_max2.setGeometry(QtCore.QRect(385, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_umi_max2.setFont(font)
        self.label_umi_max2.setObjectName("label_umi_max2")
        self.label_fluxo_max2 = QtWidgets.QLabel(Dialog_Param)
        self.label_fluxo_max2.setGeometry(QtCore.QRect(525, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_fluxo_max2.setFont(font)
        self.label_fluxo_max2.setObjectName("label_fluxo_max2")
        self.label_xx_max2 = QtWidgets.QLabel(Dialog_Param)
        self.label_xx_max2.setGeometry(QtCore.QRect(665, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_xx_max2.setFont(font)
        self.label_xx_max2.setObjectName("label_xx_max2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 210, 106, 32))
        self.pushButton_2.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 210, 106, 32))
        self.pushButton_3.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 210, 106, 32))
        self.pushButton_4.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_5.setGeometry(QtCore.QRect(630, 210, 106, 32))
        self.pushButton_5.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_6.setGeometry(QtCore.QRect(625, 450, 106, 32))
        self.pushButton_6.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.text_fluxo_min = QtWidgets.QTextEdit(Dialog_Param)
        self.text_fluxo_min.setGeometry(QtCore.QRect(485, 370, 104, 78))
        self.text_fluxo_min.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_fluxo_min.setObjectName("text_fluxo_min")
        self.label_xx_min = QtWidgets.QLabel(Dialog_Param)
        self.label_xx_min.setGeometry(QtCore.QRect(640, 330, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_xx_min.setFont(font)
        self.label_xx_min.setObjectName("label_xx_min")
        self.label_temp_min2 = QtWidgets.QLabel(Dialog_Param)
        self.label_temp_min2.setGeometry(QtCore.QRect(240, 350, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_min2.setFont(font)
        self.label_temp_min2.setObjectName("label_temp_min2")
        self.label_umi_min2 = QtWidgets.QLabel(Dialog_Param)
        self.label_umi_min2.setGeometry(QtCore.QRect(380, 350, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_umi_min2.setFont(font)
        self.label_umi_min2.setObjectName("label_umi_min2")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_7.setGeometry(QtCore.QRect(65, 450, 106, 32))
        self.pushButton_7.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_8.setGeometry(QtCore.QRect(485, 450, 106, 32))
        self.pushButton_8.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_fluxo_min = QtWidgets.QLabel(Dialog_Param)
        self.label_fluxo_min.setGeometry(QtCore.QRect(495, 330, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_fluxo_min.setFont(font)
        self.label_fluxo_min.setObjectName("label_fluxo_min")
        self.label_pressao_min = QtWidgets.QLabel(Dialog_Param)
        self.label_pressao_min.setGeometry(QtCore.QRect(90, 330, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pressao_min.setFont(font)
        self.label_pressao_min.setObjectName("label_pressao_min")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_9.setGeometry(QtCore.QRect(345, 450, 106, 32))
        self.pushButton_9.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.text_pressao_min = QtWidgets.QTextEdit(Dialog_Param)
        self.text_pressao_min.setGeometry(QtCore.QRect(65, 370, 104, 78))
        self.text_pressao_min.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_pressao_min.setObjectName("text_pressao_min")
        self.label_pressao_min2 = QtWidgets.QLabel(Dialog_Param)
        self.label_pressao_min2.setGeometry(QtCore.QRect(100, 350, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pressao_min2.setFont(font)
        self.label_pressao_min2.setObjectName("label_pressao_min2")
        self.text_umi_min = QtWidgets.QTextEdit(Dialog_Param)
        self.text_umi_min.setGeometry(QtCore.QRect(345, 370, 104, 78))
        self.text_umi_min.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_umi_min.setObjectName("text_umi_min")
        self.text_xxxxx_min = QtWidgets.QTextEdit(Dialog_Param)
        self.text_xxxxx_min.setGeometry(QtCore.QRect(625, 370, 104, 78))
        self.text_xxxxx_min.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_xxxxx_min.setObjectName("text_xxxxx_min")
        self.label_umi_min = QtWidgets.QLabel(Dialog_Param)
        self.label_umi_min.setGeometry(QtCore.QRect(365, 330, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_umi_min.setFont(font)
        self.label_umi_min.setObjectName("label_umi_min")
        self.label_temp_min = QtWidgets.QLabel(Dialog_Param)
        self.label_temp_min.setGeometry(QtCore.QRect(210, 330, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_min.setFont(font)
        self.label_temp_min.setObjectName("label_temp_min")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog_Param)
        self.pushButton_10.setGeometry(QtCore.QRect(205, 450, 106, 32))
        self.pushButton_10.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_xx_min_2 = QtWidgets.QLabel(Dialog_Param)
        self.label_xx_min_2.setGeometry(QtCore.QRect(660, 350, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_xx_min_2.setFont(font)
        self.label_xx_min_2.setObjectName("label_xx_min_2")
        self.text_temp_min = QtWidgets.QTextEdit(Dialog_Param)
        self.text_temp_min.setGeometry(QtCore.QRect(205, 370, 104, 78))
        self.text_temp_min.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.text_temp_min.setObjectName("text_temp_min")
        self.label_fluxo_min2 = QtWidgets.QLabel(Dialog_Param)
        self.label_fluxo_min2.setGeometry(QtCore.QRect(520, 350, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_fluxo_min2.setFont(font)
        self.label_fluxo_min2.setObjectName("label_fluxo_min2")
        self.btn_voltar = QtWidgets.QPushButton(Dialog_Param)
        self.btn_voltar.setGeometry(QtCore.QRect(10, 20, 41, 32))
        self.btn_voltar.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 3px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.btn_voltar.setObjectName("btn_voltar")
        self.label_alt_1 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_1.setEnabled(True)
        self.label_alt_1.setGeometry(QtCore.QRect(75, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_1.setFont(font)
        self.label_alt_1.setText("")
        self.label_alt_1.setObjectName("label_alt_1")
        self.label_alt_2 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_2.setGeometry(QtCore.QRect(215, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_2.setFont(font)
        self.label_alt_2.setText("")
        self.label_alt_2.setObjectName("label_alt_2")
        self.label_alt_4 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_4.setGeometry(QtCore.QRect(495, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_4.setFont(font)
        self.label_alt_4.setText("")
        self.label_alt_4.setObjectName("label_alt_4")
        self.label_alt_3 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_3.setGeometry(QtCore.QRect(355, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_3.setFont(font)
        self.label_alt_3.setText("")
        self.label_alt_3.setObjectName("label_alt_3")
        self.label_alt_5 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_5.setGeometry(QtCore.QRect(640, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_5.setFont(font)
        self.label_alt_5.setText("")
        self.label_alt_5.setObjectName("label_alt_5")
        self.label_alt_6 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_6.setGeometry(QtCore.QRect(70, 490, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_6.setFont(font)
        self.label_alt_6.setText("")
        self.label_alt_6.setObjectName("label_alt_6")
        self.label_alt_7 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_7.setGeometry(QtCore.QRect(210, 490, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_7.setFont(font)
        self.label_alt_7.setText("")
        self.label_alt_7.setObjectName("label_alt_7")
        self.label_alt_8 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_8.setGeometry(QtCore.QRect(350, 490, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_8.setFont(font)
        self.label_alt_8.setText("")
        self.label_alt_8.setObjectName("label_alt_8")
        self.label_alt_9 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_9.setGeometry(QtCore.QRect(490, 490, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_9.setFont(font)
        self.label_alt_9.setText("")
        self.label_alt_9.setObjectName("label_alt_9")
        self.label_alt_10 = QtWidgets.QLabel(Dialog_Param)
        self.label_alt_10.setGeometry(QtCore.QRect(635, 490, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt_10.setFont(font)
        self.label_alt_10.setText("")
        self.label_alt_10.setObjectName("label_alt_10")

        self.retranslateUi(Dialog_Param)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Param)

    def retranslateUi(self, Dialog_Param):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Param.setWindowTitle(_translate("Dialog_Param", "Dialog"))
        self.text_umi_max.setHtml(_translate("Dialog_Param", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_pressao_max.setText(_translate("Dialog_Param", "Pressão"))
        self.label_temp_max.setText(_translate("Dialog_Param", "Temperatura"))
        self.label_umi_max.setText(_translate("Dialog_Param", "Umidade"))
        self.label_fluxo_max.setText(_translate("Dialog_Param", "Fluxo de ar"))
        self.label_xx_max.setText(_translate("Dialog_Param", "XXXXXXX"))
        self.label_superior.setText(_translate("Dialog_Param", "Para alterar os parâmetros, basta escolher o valor desejado e clicar no botão MODIFICAR"))
        self.pushButton.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.label_pressao_max2.setText(_translate("Dialog_Param", "MÁX"))
        self.label_temp_max2.setText(_translate("Dialog_Param", "MÁX"))
        self.label_umi_max2.setText(_translate("Dialog_Param", "MÁX"))
        self.label_fluxo_max2.setText(_translate("Dialog_Param", "MÁX"))
        self.label_xx_max2.setText(_translate("Dialog_Param", "MÁX"))
        self.pushButton_2.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.pushButton_3.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.pushButton_4.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.pushButton_5.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.pushButton_6.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.label_xx_min.setText(_translate("Dialog_Param", "XXXXXXX"))
        self.label_temp_min2.setText(_translate("Dialog_Param", "MÍN"))
        self.label_umi_min2.setText(_translate("Dialog_Param", "MÍN"))
        self.pushButton_7.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.pushButton_8.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.label_fluxo_min.setText(_translate("Dialog_Param", "Fluxo de ar"))
        self.label_pressao_min.setText(_translate("Dialog_Param", "Pressão"))
        self.pushButton_9.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.label_pressao_min2.setText(_translate("Dialog_Param", "MÍN"))
        self.label_umi_min.setText(_translate("Dialog_Param", "Umidade"))
        self.label_temp_min.setText(_translate("Dialog_Param", "Temperatura"))
        self.pushButton_10.setText(_translate("Dialog_Param", "MODIFICAR"))
        self.label_xx_min_2.setText(_translate("Dialog_Param", "MÍN"))
        self.label_fluxo_min2.setText(_translate("Dialog_Param", "MÍN"))
        self.btn_voltar.setText(_translate("Dialog_Param", "<<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Param = QtWidgets.QDialog()
    ui = Ui_Dialog_Param()
    ui.setupUi(Dialog_Param)
    Dialog_Param.show()
    sys.exit(app.exec_())

